context:
  name: unison
  version: "2.54.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/bcpierce00/unison/archive/v${{ version }}.tar.gz
  sha256: 0f14154611a2dfebb8c229be85ceda29a750eace4fb75d06e0d43fe5b58a6e87

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - ocaml
    - pkg-config
    - inotify

tests:
  - script:
      - unison -version
  - package_contents:
      bin:
        - unison

about:
  homepage: https://github.com/bcpierce00/unison
  summary: Unison file synchronizer
  license: GPL-3.0-only
  license_file: LICENSE
  repository: https://github.com/bcpierce00/unison

extra:
  recipe-maintainers:
    - niklasl
